### ISSUE TITLE
IOError: File not found 

### ISSUE THREAD

**Issue by pawisoon** [dhylands/python_lcd#1]
So I got this error while trying to use your lib. 
I suppose this is because Beaglebone black doesn't have device tree enabled.
Do you know how to solve it?

Cheers
Paul 

```
debian@arm:~/python_lcd$ sudo python lcd/i2c_lcd.py
Traceback (most recent call last):
  File "lcd/i2c_lcd.py", line 125, in <module>
    test_main()
  File "lcd/i2c_lcd.py", line 93, in test_main
    lcd = I2cLcd(1, 0x27, 2, 16)
  File "lcd/i2c_lcd.py", line 24, in __init__
    self.bus = smbus.SMBus(port)
IOError: [Errno 2] No such file or directory
```

**Comment by dhylands** [comment]
@pawisoon  I haven't used my BeagleBone Black in a while.

IIRC, You should see /dev/i2c-X  where X is the port number.

I found some information here: http://datko.net/2013/11/03/bbb_i2c/ but haven't done this myself, so I don't know if its correct or not.
